version: '3.8'

services:
  # API de Contactos
  api-contactos:
    build: .
    container_name: contactos-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/usr/src/app/src:ro  # Solo lectura para desarrollo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Nginx como reverse proxy (opcional para producción)
  nginx:
    image: nginx:alpine
    container_name: contactos-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-contactos
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - production  # Solo se ejecuta con --profile production

networks:
  app-network:
    driver: bridge

volumes:
  api-data:
    driver: local